<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BarAccount</name>
   <tag></tag>
   <elementGuidId>fa1f3fe7-a4ca-4ab4-aeac-bcfa113245ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#navbarAccount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='navbarAccount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Show/hide account menu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3c50114-5207-4352-b491-ad7dc7f439ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Show/hide account menu</value>
      <webElementGuid>1d219d90-2c94-4257-8406-70b6d25d7292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarAccount</value>
      <webElementGuid>beb33d8a-f42c-4979-9d4c-20568fb61f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-menu-trigger buttons mat-button mat-button-base cdk-focused cdk-mouse-focused</value>
      <webElementGuid>f4a21c00-7fd3-4003-b080-e60583b92621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>886e884d-712e-4f6a-b692-6c8c9d3cc641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> account_circle  Account </value>
      <webElementGuid>455662b3-1f43-402c-b060-3d455d396853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarAccount&quot;)</value>
      <webElementGuid>c41fd89a-aa4f-4a5c-83b0-5ddd0edca7ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='navbarAccount']</value>
      <webElementGuid>65897191-791a-48d3-a803-9988bc368980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OWASP Juice Shop'])[4]/following::button[1]</value>
      <webElementGuid>49d12f04-3680-46d1-8592-8497295c7f34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='v17.1.1'])[1]/following::button[3]</value>
      <webElementGuid>bae526c2-9093-4ce8-8ad1-5c9cf42d468c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>ccee36d1-3cf0-4ec6-bf01-5f138549f351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'navbarAccount' and (text() = ' account_circle  Account ' or . = ' account_circle  Account ')]</value>
      <webElementGuid>947c87b7-2290-4ab8-92d2-353add2c1927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
