<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Your eldest siblings middle name  Mothers maiden name  Mothers birth date (MMDDYY)  Fathers birth date (MMDDYY)  Maternal grandmothers first name  Paternal grandmothers first name  Name of your favorite pet  Last nam</name>
   <tag></tag>
   <elementGuidId>225a0073-3bd3-488b-bfdb-76536f7e6e6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-select-14-panel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-14-panel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox[name=&quot;Selection list for the security question&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>582e8d22-4778-4d41-b991-c402be9ae8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>3d8015a8-818e-4a72-912c-d2afb4eed1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>186493d6-b51a-449e-ba62-8faff2b757b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c30-46 ng-trigger ng-trigger-transformPanel mat-select-panel mat-accent</value>
      <webElementGuid>2eabfbac-65f3-4d2b-b66b-e174485d3d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-select-14-panel</value>
      <webElementGuid>21268704-152a-48cc-b083-f545cc0b359b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-multiselectable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1637b83b-6baa-441e-95bd-7203db13ce57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Selection list for the security question</value>
      <webElementGuid>8c90881c-aa3c-4d35-b363-602dc243cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Your eldest siblings middle name?  Mother's maiden name?  Mother's birth date? (MM/DD/YY)  Father's birth date? (MM/DD/YY)  Maternal grandmother's first name?  Paternal grandmother's first name?  Name of your favorite pet?  Last name of dentist when you were a teenager? (Do not include 'Dr.')  Your ZIP/postal code when you were a teenager?  Company you first work for as an adult?  Your favorite book?  Your favorite movie?  Number of one of your customer or ID cards?  What's your favorite place to go hiking? </value>
      <webElementGuid>3163668d-feed-4611-9ef2-46cedc933e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-14-panel&quot;)</value>
      <webElementGuid>a2abdec1-2e97-4819-a8be-6cbf8ffd04a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-select-14-panel']</value>
      <webElementGuid>cc56bb86-93d0-4329-a786-6d71e0445bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-14']/div/div</value>
      <webElementGuid>7c69da55-e90d-4c48-9320-dc17ed62d6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already a customer?'])[1]/following::div[7]</value>
      <webElementGuid>100997ef-912e-4c99-a9fd-047db69c4aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='person_add'])[1]/following::div[8]</value>
      <webElementGuid>14bff5b4-6aff-4537-bc1c-c200343a59aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>a5fd676d-93f8-443d-9a52-9396650d3544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-select-14-panel' and (text() = concat(&quot; Your eldest siblings middle name?  Mother&quot; , &quot;'&quot; , &quot;s maiden name?  Mother&quot; , &quot;'&quot; , &quot;s birth date? (MM/DD/YY)  Father&quot; , &quot;'&quot; , &quot;s birth date? (MM/DD/YY)  Maternal grandmother&quot; , &quot;'&quot; , &quot;s first name?  Paternal grandmother&quot; , &quot;'&quot; , &quot;s first name?  Name of your favorite pet?  Last name of dentist when you were a teenager? (Do not include &quot; , &quot;'&quot; , &quot;Dr.&quot; , &quot;'&quot; , &quot;)  Your ZIP/postal code when you were a teenager?  Company you first work for as an adult?  Your favorite book?  Your favorite movie?  Number of one of your customer or ID cards?  What&quot; , &quot;'&quot; , &quot;s your favorite place to go hiking? &quot;) or . = concat(&quot; Your eldest siblings middle name?  Mother&quot; , &quot;'&quot; , &quot;s maiden name?  Mother&quot; , &quot;'&quot; , &quot;s birth date? (MM/DD/YY)  Father&quot; , &quot;'&quot; , &quot;s birth date? (MM/DD/YY)  Maternal grandmother&quot; , &quot;'&quot; , &quot;s first name?  Paternal grandmother&quot; , &quot;'&quot; , &quot;s first name?  Name of your favorite pet?  Last name of dentist when you were a teenager? (Do not include &quot; , &quot;'&quot; , &quot;Dr.&quot; , &quot;'&quot; , &quot;)  Your ZIP/postal code when you were a teenager?  Company you first work for as an adult?  Your favorite book?  Your favorite movie?  Number of one of your customer or ID cards?  What&quot; , &quot;'&quot; , &quot;s your favorite place to go hiking? &quot;))]</value>
      <webElementGuid>0ba79468-3cf6-48e2-9bd6-d8c2fc6347c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
